

name: Build LaTeX document
on:
  push:
    tags:
      - 'v*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Rename PDF
        run: mv main.pdf paper-${{ steps.get_version.outputs.VERSION }}.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./paper-${{ steps.get_version.outputs.VERSION }}.pdf
          asset_name: paper-${{ steps.get_version.outputs.VERSION }}.pdf
          asset_content_type: application/pdf
      # - uses: mkrakowitzer/actions-googledrive@master
      #   with:
      #     upload-from: ./paper-${{ steps.get_version.outputs.VERSION }}.pdf
      #     upload-to: some-directory/
      #     skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE }}
      #     google-client-id: ${{ secrets.DRIVE_CLIENT_ID }}
      #     google-client-secret: ${{ secrets.DRIVE_CLIENT_SECRET }}
